/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PromosRouteImport } from './routes/promos'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as OpinionesRouteImport } from './routes/opiniones'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const PromosRoute = PromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinionesRoute = OpinionesRouteImport.update({
  id: '/opiniones',
  path: '/opiniones',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/menu': typeof MenuRoute
  '/nosotros': typeof NosotrosRoute
  '/opiniones': typeof OpinionesRoute
  '/productos': typeof ProductosRoute
  '/promos': typeof PromosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/menu': typeof MenuRoute
  '/nosotros': typeof NosotrosRoute
  '/opiniones': typeof OpinionesRoute
  '/productos': typeof ProductosRoute
  '/promos': typeof PromosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/menu': typeof MenuRoute
  '/nosotros': typeof NosotrosRoute
  '/opiniones': typeof OpinionesRoute
  '/productos': typeof ProductosRoute
  '/promos': typeof PromosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/menu'
    | '/nosotros'
    | '/opiniones'
    | '/productos'
    | '/promos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/menu'
    | '/nosotros'
    | '/opiniones'
    | '/productos'
    | '/promos'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/menu'
    | '/nosotros'
    | '/opiniones'
    | '/productos'
    | '/promos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  MenuRoute: typeof MenuRoute
  NosotrosRoute: typeof NosotrosRoute
  OpinionesRoute: typeof OpinionesRoute
  ProductosRoute: typeof ProductosRoute
  PromosRoute: typeof PromosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/promos': {
      id: '/promos'
      path: '/promos'
      fullPath: '/promos'
      preLoaderRoute: typeof PromosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opiniones': {
      id: '/opiniones'
      path: '/opiniones'
      fullPath: '/opiniones'
      preLoaderRoute: typeof OpinionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  MenuRoute: MenuRoute,
  NosotrosRoute: NosotrosRoute,
  OpinionesRoute: OpinionesRoute,
  ProductosRoute: ProductosRoute,
  PromosRoute: PromosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
